import { useState } from "react";
import { authFetch } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from"@/components/ui/card";
import { Button } from"@/components/ui/button";
import { Input } from"@/components/ui/input";
import { Badge } from"@/components/ui/badge";
import { Label } from"@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from"@/components/ui/select";
import { motion } from"framer-motion";
import {
  Wand2,
  Sparkles,
  BookOpen,
  Clock,
  Target,
  Users,
  Download,
  RefreshCw,
  CheckCircle,
} from"lucide-react";

interface LessonPlan {
  title: string;
  duration: number;
  objectives: string[];
  materials: string[];
  activities: Array<{
    name: string;
    duration: number;
    description: string;
  }>;
  assessment: string[];
}

export function AILessonPlanner() {
  const [topic, setTopic] = useState("");
  const [duration, setDuration] = useState<number>(60);
  const [level, setLevel] = useState("intermediate");
  const [isGenerating, setIsGenerating] = useState(false);
  const [lessonPlan, setLessonPlan] = useState<LessonPlan | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);
    setError(null);
    try {
      const data = await authFetch("/api/ai/lesson-plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic, duration, difficulty: level }),
      }) as LessonPlan;
      // #118: guard against missing/malformed fields from API response
      const validated: LessonPlan = {
        title: typeof data.title === "string" ? data.title : topic,
        duration: typeof data.duration === "number" ? data.duration : duration,
        objectives: Array.isArray(data.objectives) ? data.objectives : [],
        materials: Array.isArray(data.materials) ? data.materials : [],
        activities: Array.isArray(data.activities) ? data.activities : [],
        assessment: Array.isArray(data.assessment) ? data.assessment : [],
      };
      setLessonPlan(validated);
    } catch (err: Error | unknown) {
      setError((err as Error).message || "Failed to generate lesson plan. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!lessonPlan) return;

    const content = `# Lesson Plan: ${lessonPlan.title}\nDuration: ${lessonPlan.duration} minutes | Level: ${level}\n\n## Learning Objectives\n${lessonPlan.objectives.map((obj, i) => `${i + 1}. ${obj}`).join('\n')}\n\n## Required Materials\n${lessonPlan.materials.map((mat) => `- ${mat}`).join('\n')}\n\n## Lesson Activities\n${lessonPlan.activities.map((activity, i) => `\n### ${i + 1}. ${activity.name} (${activity.duration} min)\n${activity.description}`).join('\n')}\n\n## Assessment Methods\n${lessonPlan.assessment.map((method) => `- ${method}`).join('\n')}\n\n---\nGenerated by TutorBridge AI Lesson Planner`;

    const blob = new Blob([content], { type:"text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lesson-plan-${topic.replace(/\s+/g,"-")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card className="border-2 bg-white dark:bg-slate-900 border-purple-200 dark:border-purple-800">
        <CardHeader className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/50 dark:to-pink-950/50">
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="w-5 h-5 text-primary" />
            <span>AI Lesson Planner</span>
            <Badge variant="secondary" className="ml-auto">
              <Sparkles className="w-3 h-3 mr-1" />
              For Teachers
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Generate a comprehensive lesson plan tailored to your topic and student level in seconds
          </p>

          <div className="grid gap-4">
            <div>
              <Label htmlFor="topic">Lesson Topic *</Label>
              <Input
                id="topic"
                placeholder="e.g., Introduction to Variables in Programming"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                className="mt-1.5"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="duration">Duration (minutes)</Label>
                <Select value={String(duration)} onValueChange={(val) => setDuration(Number(val))}>
                  <SelectTrigger className="mt-1.5">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="30">30 minutes</SelectItem>
                    <SelectItem value="45">45 minutes</SelectItem>
                    <SelectItem value="60">60 minutes</SelectItem>
                    <SelectItem value="90">90 minutes</SelectItem>
                    <SelectItem value="120">120 minutes</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="level">Student Level</Label>
                <Select value={level} onValueChange={setLevel}>
                  <SelectTrigger className="mt-1.5">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="beginner">Beginner</SelectItem>
                    <SelectItem value="intermediate">Intermediate</SelectItem>
                    <SelectItem value="advanced">Advanced</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <Button
              onClick={handleGenerate}
              disabled={!topic.trim() || isGenerating}
              className="w-full neon-btn bg-primary"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating Lesson Plan...
                </>
              ) : (
                <>
                  <Wand2 className="w-4 h-4 mr-2" />
                  Generate Lesson Plan
                </>
              )}
            </Button>
            {error && (
              <p className="text-sm text-destructive text-center">{error}</p>
            )}
          </div>
        </CardContent>
      </Card>

      {lessonPlan && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          <Card className="border-2">
            <CardContent className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-xl font-bold font-display mb-1">
                    {lessonPlan.title}
                  </h3>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Clock className="w-4 h-4" />
                      {lessonPlan.duration} min
                    </span>
                    <Badge variant="outline" className="capitalize">
                      {level}
                    </Badge>
                  </div>
                </div>
                <Button
                  onClick={handleDownload}
                  variant="outline"
                  size="sm"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card className="border-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <Target className="w-5 h-5 text-primary" />
                <span>Learning Objectives</span>
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {lessonPlan.objectives.map((objective, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="flex gap-3 p-3 rounded-lg border"
                >
                  <CheckCircle className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                  <p className="text-sm">{objective}</p>
                </motion.div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <BookOpen className="w-5 h-5 text-primary" />
                <span>Required Materials</span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-2">
                {lessonPlan.materials.map((material, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <Badge variant="secondary" className="w-full justify-start">
                      {material}
                    </Badge>
                  </motion.div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="border-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <Users className="w-5 h-5 text-primary" />
                <span>Lesson Activities</span>
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="relative">
                <div className="absolute left-6 top-8 bottom-8 w-0.5 bg-primary/20" />

                {lessonPlan.activities.map((activity, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="relative flex gap-4 mb-6"
                  >
                    <div className="relative w-12 h-12 rounded-full border-2 border-primary/50 flex items-center justify-center shrink-0">
                      <span className="text-sm font-bold">{index + 1}</span>
                    </div>

                    <Card className="flex-1 card-hover-lift border">
                      <CardContent className="p-4">
                        <div className="flex items-start justify-between mb-2">
                          <h4 className="font-semibold text-sm">
                            {activity.name}
                          </h4>
                          <Badge variant="outline" className="text-xs">
                            <Clock className="w-3 h-3 mr-1" />
                            {activity.duration} min
                          </Badge>
                        </div>
                        <p className="text-sm text-muted-foreground">
                          {activity.description}
                        </p>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="border-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <CheckCircle className="w-5 h-5 text-primary" />
                <span>Assessment Methods</span>
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {lessonPlan.assessment.map((method, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="flex gap-3 p-3 rounded-lg border"
                >
                  <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 shrink-0" />
                  <p className="text-sm">{method}</p>
                </motion.div>
              ))}
            </CardContent>
          </Card>

          <Button
            onClick={handleGenerate}
            variant="outline"
            className="w-full"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Generate Another Version
          </Button>
        </motion.div>
      )}
    </div>
  );
}
