import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { motion } from "framer-motion";
import {
  FileText,
  Sparkles,
  Download,
  Copy,
  CheckCircle,
  Lightbulb,
  ListChecks,
  ArrowRight,
  Loader2,
  RefreshCw,
} from "lucide-react";
import { authFetch } from "@/lib/api";
import { Link } from "wouter";

interface ClassSummary {
  keyPoints: string[];
  takeaways: string[];
  practiceQuestions: string[];
  nextSteps: string[];
}

interface AutoSummariesProps {
  classId: number;
  classTitle: string;
}

export function AutoSummaries({ classId, classTitle }: AutoSummariesProps) {
  const [copied, setCopied] = useState(false);
  const [summary, setSummary] = useState<ClassSummary | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedDate, setGeneratedDate] = useState<string | null>(null);

  // Restore cached summary on mount — expire after 7 days
  const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
  useEffect(() => {
    try {
      const cached = localStorage.getItem(`ai_summary_${classId}`);
      if (cached) {
        const { summary: s, date, cachedAt } = JSON.parse(cached);
        if (cachedAt && Date.now() - cachedAt < CACHE_TTL_MS) {
          setSummary(s);
          setGeneratedDate(date);
        } else {
          localStorage.removeItem(`ai_summary_${classId}`);
        }
      }
    } catch {}
  }, [classId]);

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await authFetch("/api/ai/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ classTitle }),
      });
      const dateStr = new Date().toLocaleDateString();
      setSummary(data);
      setGeneratedDate(dateStr);
      try { localStorage.setItem(`ai_summary_${classId}`, JSON.stringify({ summary: data, date: dateStr, cachedAt: Date.now() })); } catch {}
    } catch (err: any) {
      setError(err.message || "Failed to generate summary. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    if (!summary) return;
    const content = `# ${classTitle} - Class Summary\nGenerated: ${generatedDate}\n\n## Key Concepts Covered\n${summary.keyPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}\n\n## Important Takeaways\n${summary.takeaways.map((point, i) => `${i + 1}. ${point}`).join('\n')}\n\n## Practice Questions\n${summary.practiceQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\n## Suggested Next Steps\n${summary.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}\n\n---\nGenerated by TutorBridge AI`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${classTitle.replace(/\s+/g, "-")}-summary.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    if (!summary) return;
    const fullContent = [
      `## Key Concepts\n${summary.keyPoints.join("\n")}`,
      `\n## Takeaways\n${summary.takeaways.join("\n")}`,
      `\n## Practice Questions\n${summary.practiceQuestions.join("\n")}`,
      `\n## Next Steps\n${summary.nextSteps.join("\n")}`,
    ].join("\n");
    navigator.clipboard.writeText(fullContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className="border-2 bg-white dark:bg-slate-900 border-purple-200 dark:border-purple-800">
      <CardHeader className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/50 dark:to-pink-950/50">
        <div className="flex items-start justify-between">
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            <span>AI-Generated Summary</span>
          </CardTitle>
          <Badge variant="secondary" className="shrink-0">
            <Sparkles className="w-3 h-3 mr-1" />
            AI Powered
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {!summary ? (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">
              Generate an AI-powered summary for <span className="font-medium text-foreground">{classTitle}</span> including key points, takeaways, practice questions, and next steps.
            </p>
            <Button
              className="w-full neon-btn bg-primary"
              onClick={handleGenerate}
              disabled={isLoading}
            >
              {isLoading ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating Summary...</>
              ) : (
                <><Sparkles className="w-4 h-4 mr-2" /> Generate Class Summary</>
              )}
            </Button>
            {error && <p className="text-sm text-destructive text-center">{error}</p>}
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">Generated: {generatedDate}</span>
              <div className="flex items-center gap-2">
                <Button size="sm" variant="outline" onClick={handleCopy} className="h-8">
                  {copied ? (
                    <><CheckCircle className="w-3 h-3 mr-1" /> Copied!</>
                  ) : (
                    <><Copy className="w-3 h-3 mr-1" /> Copy</>
                  )}
                </Button>
                <Button size="sm" variant="outline" onClick={handleDownload} className="h-8">
                  <Download className="w-3 h-3 mr-1" /> Download
                </Button>
              </div>
            </div>

            <Tabs defaultValue="key-points" className="w-full">
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="key-points" className="text-xs">Key Points</TabsTrigger>
                <TabsTrigger value="takeaways" className="text-xs">Takeaways</TabsTrigger>
                <TabsTrigger value="practice" className="text-xs">Practice</TabsTrigger>
                <TabsTrigger value="next-steps" className="text-xs">Next Steps</TabsTrigger>
              </TabsList>

              <TabsContent value="key-points" className="space-y-3 mt-4">
                {(summary.keyPoints || []).map((point, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="flex gap-3 p-3 rounded-lg border"
                  >
                    <div className="w-6 h-6 rounded-full bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center shrink-0 mt-0.5">
                      <span className="text-xs font-bold text-white">{index + 1}</span>
                    </div>
                    <p className="text-sm flex-1">{point}</p>
                  </motion.div>
                ))}
              </TabsContent>

              <TabsContent value="takeaways" className="space-y-3 mt-4">
                {(summary.takeaways || []).map((takeaway, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="flex gap-3 p-3 rounded-lg border"
                  >
                    <Lightbulb className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                    <p className="text-sm flex-1">{takeaway}</p>
                  </motion.div>
                ))}
              </TabsContent>

              <TabsContent value="practice" className="space-y-3 mt-4">
                {(summary.practiceQuestions || []).map((question, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="p-3 rounded-lg border"
                  >
                    <div className="flex items-start gap-2 mb-2">
                      <Badge variant="outline" className="text-xs">Q{index + 1}</Badge>
                    </div>
                    <p className="text-sm">{question}</p>
                  </motion.div>
                ))}
                <Link href={`/classes/${classId}`}>
                  <Button className="w-full neon-btn bg-primary" size="sm">
                    <ListChecks className="w-4 h-4 mr-2" />
                    Take Practice Quiz
                  </Button>
                </Link>
              </TabsContent>

              <TabsContent value="next-steps" className="space-y-3 mt-4">
                {(summary.nextSteps || []).map((step, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="flex items-start gap-3 p-3 rounded-lg border group hover:border-primary/50 transition-colors"
                  >
                    <CheckCircle className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                    <p className="text-sm flex-1">{step}</p>
                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors shrink-0 mt-0.5" />
                  </motion.div>
                ))}
              </TabsContent>
            </Tabs>

            <Button variant="outline" className="w-full" onClick={handleGenerate} disabled={isLoading}>
              {isLoading ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Regenerating...</>
              ) : (
                <><RefreshCw className="w-4 h-4 mr-2" /> Regenerate Summary</>
              )}
            </Button>

            <div className="flex items-start gap-2 p-3 rounded-lg bg-muted/30 text-xs text-muted-foreground">
              <Sparkles className="w-4 h-4 shrink-0 mt-0.5 text-primary" />
              <p>
                This summary was automatically generated by AI to help you review key concepts.
                Always refer to your class materials for complete information.
              </p>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
